# Generated by Django 6.0.1 on 2026-01-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_resume_extracted_text_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='error_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
